### ISSUE TITLE
[BUG]Xcode Missing package product 

### ISSUE THREAD

**Issue by lichadehehehe** [AgoraIO-Community/AR-Remote-Support#26]
**Describe the bug**
"Missing package product" while compiling the project. All dependencies failed to load.

**To Reproduce**
1. Open the project in Xcode.
2. Input app ID into AppKeys.swift.
3. Wait until all remote packages are fetched.
4. Click the build project button.
5. Error of missing package product shows up.

**Expected behavior**
Project built successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/83261960/186301512-b200a26a-d172-44e0-817c-19ddc84231c6.png)

**
 - Device: [Macbook Pro 14-inches 2021 with M1 Pro Apple Silicon]
 - OS: [macOS Monterey 12.5]
 - Xcode Version [13.4.1]

**Comment by planetMatrix** [comment]
Same here . @digitallysavvy please guide

**Comment by digitallysavvy** [comment]
@maxxfrazer

**Comment by maxxfrazer** [comment]
resetting the package caches should do the trick.
click help at the top and type in "package caches", the option should appear there.

**Comment by planetMatrix** [comment]
I tried that option multiple times...at least for me it did not work, may be I'm doing something wrong?
<img width="977" alt="Screenshot 2022-09-22 at 12 49 33 PM" src="https://user-images.githubusercontent.com/38416064/191683431-033ba6d8-3b44-41c1-a212-19933be7add5.png">

**Comment by maxxfrazer** [comment]
I see - what I put will help with the error messages at the start of this issue.

from the ss you gave, looks like it's looking for some pre-release versions of several packages. we haven't updated this in a little while, I'll patch it up now.

**Comment by planetMatrix** [comment]
Awesome @maxxfrazer ... many thanks for swift support.. This  gives confidence in using your sdk Take care

**Comment by maxxfrazer** [comment]
okay, I've taken a look and it looks like Xcode 14 has a new warning/error so that's fun 😄

to summarise - video uikit is on version 4.0.0, the sdk (for reasons that I am doing my best to get rid of) released the unstable version 4.0.0-r.3.
Xcode now doesn't like when a stable package depends on an unstable one. sigh.

Patch incoming on this repo in just a second.

**Comment by maxxfrazer** [comment]
Give the branch [4.x-uikit](https://github.com/AgoraIO-Community/AR-Remote-Support/tree/4.x-uikit) a try. I had a go locally and it's building okay now at least, but still has that warning on the side about unstable versions. possibly due to caching.

I messed up my local swift package cache, moving these around etc, a clear of `~/Library/Developer/Xcode/DerivedData` did the trick.

**Comment by planetMatrix** [comment]
Perfect... build ... Many thanks

**Comment by planetMatrix** [comment]
Don't know if its related to this but on the helper side I get black screen,
On other side I'm receiving both Audio and Video from helper device
However on helper side only Audio from other user is transmitting and **not the video**

![IMG_8062](https://user-images.githubusercontent.com/38416064/191734739-35031a0f-6fe4-4f8d-bd11-0fc67c582a7a.PNG)

**Comment by maxxfrazer** [comment]
I just had a quick look at the dependency we use for capturing the SceneKit scene… this may be a problem coming from that package due to a change in iOS 16

https://github.com/AFathi/ARVideoKit/issues/136

**Comment by planetMatrix** [comment]
BTW I'm on 15.6.1 on iPhone X
and 15.4 on iPad Pro

**Comment by maxxfrazer** [comment]
based on that I thought that the external video capture was broken in the SDK for a moment there… but just created an example that works okay.
I think it's something to do with the pixel buffer ARVideoKit is spitting out; this was working previously.

The image seems fine locally before sending into the SDK... I'll let you know if I get anywhere, this repo is due for a refresh in any case.

**Comment by maxxfrazer** [comment]
This is fixed in SDK 4.1.0. I'll update this repo as soon as that version is out (I believe early next week)

**Comment by lichadehehehe** [comment]
Thank you maxxfrazer for looking into this issue. The [4.x-uikit](https://github.com/AgoraIO-Community/AR-Remote-Support/tree/4.x-uikit) branch can be successfully built but I still encounter the same issue as planetMatrix did. Please let me know if this is solved.

**Comment by maxxfrazer** [comment]
thanks for the reminder @lichadehehehe! the release got delayed until i left for the holidays. will update it today.

**Comment by lichadehehehe** [comment]
![image](https://user-images.githubusercontent.com/83261960/211769583-a2dc4e11-c0da-46e0-aa65-cbfc91ba472a.png)
FYI this is what the console output looks like. Looks like the touches from the helper are registered aside from the black screen.

**Comment by maxxfrazer** [comment]
All fixed on the main branch 👍
